spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    example: kafka_bank_account_stream
    
xmlapp:
  topic:
    example: kafka_xml_bank_account_stream3


logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG
